"use client";

import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { useState } from "react";

const tabs = ["UNDERSTAND", "REMEMBER", "DECIDE", "CONTROL"] as const;
type Tab = (typeof tabs)[number];

const pulse = { duration: 1.8, repeat: Infinity, repeatDelay: 2.8 };
const MiniCard = ({ title, value, active = false }: { title: string; value: string; active?: boolean }) => <div className={`rounded-lg border p-3 ${active ? "border-[#FF5A1F]/35 bg-[#FF5A1F]/[0.06]" : "border-white/[0.08] bg-black/15"}`}><p className="font-mono text-[8px] uppercase tracking-wider text-white/45">{title}</p><p className={`mt-1 text-xs font-semibold ${active ? "text-[#FF5A1F]" : "text-white/75"}`}>{value}</p></div>;

function Understand({ reduce }: { reduce: boolean | null }) {
  const intents = ["Meeting request", "Pricing question", "Objection", "Unsubscribe"];
  return <div className="grid h-full gap-4 lg:grid-cols-[.8fr_1.1fr_.8fr]"><div className="rounded-xl border border-white/[0.08] bg-black/15 p-3"><p className="font-mono text-[8px] uppercase tracking-wider text-white/40">Inbox queue</p>{["Acme — Can we talk pricing?", "Northstar — Not interested", "Vertex — Security questionnaire", "Apollo — Thursday works"].map((item, index) => <motion.div key={item} animate={!reduce && index === 0 ? { borderColor: ["rgba(255,255,255,.08)", "rgba(255,90,31,.45)", "rgba(255,255,255,.08)"] } : {}} transition={pulse} className={`mt-2 rounded-md border px-2 py-2 font-mono text-[8px] ${index === 0 ? "border-[#FF5A1F]/30 text-white" : "border-white/[0.06] text-white/35"}`}>{item}</motion.div>)}</div><div className="flex flex-col justify-center"><motion.div initial={{ x: reduce ? 0 : -18, opacity: 0 }} animate={{ x: 0, opacity: 1 }} transition={{ duration: .5 }} className="rounded-xl rounded-tl-sm border border-white/[0.1] bg-[#242424] p-4 text-sm text-white/85">Can you clarify pricing before we schedule?</motion.div><div className="relative mx-auto h-10 w-px overflow-hidden bg-white/10">{!reduce && <motion.i animate={{ y: [-8, 40] }} transition={pulse} className="absolute h-3 w-px bg-[#FF5A1F]" />}</div><div className="rounded-xl border border-[#FF5A1F]/30 bg-[#FF5A1F]/[0.05] p-4"><p className="font-mono text-[8px] uppercase tracking-wider text-white/45">Intent scan</p><div className="mt-3 grid grid-cols-2 gap-2">{intents.map((item, index) => <motion.span key={item} animate={!reduce && index === 1 ? { opacity: [0.35, 1, 1], scale: [.98, 1.02, 1] } : {}} transition={{ duration: .7, delay: index * .12 }} className={`rounded-md border px-2 py-2 text-center font-mono text-[8px] ${index === 1 ? "border-[#FF5A1F]/45 text-[#FF5A1F]" : "border-white/[0.06] text-white/30"}`}>{item}</motion.span>)}</div></div></div><div className="flex flex-col justify-center gap-2"><MiniCard title="Intent" value="Pricing objection" active /><MiniCard title="Fit" value="High" /><MiniCard title="Revenue at risk" value="$70K" active /><MiniCard title="SLA" value="14 minutes" /><MiniCard title="Policy" value="Approval required" active /></div></div>;
}

function Remember({ reduce }: { reduce: boolean | null }) {
  const events = ["Campaign — pricing concern", "Discovery — completed", "Human override — enterprise sequence", "Current reply — security review?"];
  return <div className="relative flex h-full flex-col items-center justify-center gap-5"><div className="grid w-full max-w-sm place-items-center rounded-xl border border-[#FF5A1F]/30 bg-[#FF5A1F]/[0.05] p-4"><span className="grid h-10 w-10 place-items-center rounded-full border border-white/15 bg-[#242424] text-sm text-white">SC</span><p className="mt-2 text-sm font-bold text-white">ACME CORP</p><p className="font-mono text-[8px] uppercase tracking-wider text-white/45">Sarah Chen · Enterprise account</p></div><div className="grid w-full max-w-2xl gap-2 sm:grid-cols-2">{events.map((event, index) => <motion.div key={event} initial={{ opacity: 0, y: reduce ? 0 : 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .15, duration: .35 }} className="relative rounded-lg border border-white/[0.08] bg-black/15 p-3 font-mono text-[9px] text-white/65">{event}{index < events.length - 1 && <span className="absolute -bottom-2 left-1/2 h-2 w-px bg-[#FF5A1F]/40" />}</motion.div>)}</div><div className="flex flex-wrap justify-center gap-2">{["Account", "Offer", "Brand Brain", "Previous meeting", "Applicable rule"].map((item, index) => <motion.span key={item} animate={!reduce ? { opacity: [.4, 1, .4] } : {}} transition={{ ...pulse, delay: index * .18 }} className="rounded-full border border-white/[0.1] bg-white/[0.03] px-3 py-2 font-mono text-[8px] uppercase tracking-wider text-white/65">{item}</motion.span>)}</div></div>;
}

function Decide({ reduce }: { reduce: boolean | null }) {
  const inputs = [["Intent", "Security question"], ["Prospect", "High-fit enterprise"], ["Value", "$70K"], ["Memory", "Pricing discussed"]];
  return <div className="grid h-full items-center gap-4 lg:grid-cols-[1fr_.9fr_1fr]"><div className="grid gap-2">{inputs.map(([title, value]) => <MiniCard key={title} title={title} value={value} />)}</div><div className="relative text-center"><motion.div animate={!reduce ? { boxShadow: ["0 0 0 rgba(255,90,31,0)", "0 0 26px rgba(255,90,31,.35)", "0 0 0 rgba(255,90,31,0)"] } : {}} transition={pulse} className="rounded-2xl border border-[#FF5A1F]/40 bg-[#FF5A1F]/[0.08] p-6"><p className="font-mono text-[9px] uppercase tracking-[.16em] text-[#FF5A1F]">FrameLeads</p><p className="mt-2 text-sm font-bold text-white">Decision engine</p><p className="mt-3 font-mono text-[8px] text-white/45">SEC-04 matched</p></motion.div></div><div className="grid gap-2">{["Auto reply", "Human approval", "Sales engineering", "Meeting", "Stop"].map((route, index) => <motion.div key={route} animate={!reduce && index === 2 ? { x: [0, 5, 0], borderColor: ["rgba(255,255,255,.08)", "rgba(255,90,31,.55)", "rgba(255,255,255,.08)"] } : {}} transition={pulse} className={`rounded-lg border p-3 text-sm ${index === 2 ? "border-[#FF5A1F]/35 bg-[#FF5A1F]/[0.06] text-[#FF5A1F]" : "border-white/[0.08] bg-black/15 text-white/35"}`}>{route}</motion.div>)}</div></div>;
}

function Control({ reduce }: { reduce: boolean | null }) {
  return <div className="grid h-full gap-4 md:grid-cols-2"><div className="rounded-xl border border-green-400/20 bg-green-400/[0.03] p-5"><p className="font-mono text-[8px] uppercase tracking-wider text-green-300">Routine meeting confirmation</p><div className="mt-5 flex items-center gap-3"><span className="h-3 w-3 rounded-full bg-green-400" /><span className="h-px flex-1 bg-green-400/40" /><span className="text-green-300">▣</span></div><p className="mt-5 text-sm font-bold text-white">AUTOPILOT</p><p className="mt-2 text-xs text-white/55">Calendar action continues</p></div><div className="rounded-xl border border-[#FF5A1F]/25 bg-[#FF5A1F]/[0.04] p-5"><p className="font-mono text-[8px] uppercase tracking-wider text-[#FF5A1F]">Enterprise pricing negotiation</p><div className="mt-5 flex items-center gap-3"><span className="h-3 w-3 rounded-full bg-[#FF5A1F]" /><span className="h-px flex-1 bg-[#FF5A1F]/35" /><motion.span animate={!reduce ? { rotate: [0, 0, -8, 0] } : {}} transition={{ duration: 2.5, repeat: Infinity, repeatDelay: 3 }} className="text-xl text-[#FF5A1F]">▣</motion.span></div><p className="mt-5 text-sm font-bold text-white">MANDATORY ESCALATION</p><p className="mt-2 text-xs text-white/55">Gate closed · Human review queued</p></div></div>;
}

export default function DecisionIntelligenceWalkthrough() {
  const [active, setActive] = useState<Tab>("UNDERSTAND");
  const reduceMotion = useReducedMotion();
  const Visual = active === "UNDERSTAND" ? Understand : active === "REMEMBER" ? Remember : active === "DECIDE" ? Decide : Control;
  return <div className="mx-auto mt-10 max-w-6xl"><div className="flex flex-wrap justify-center gap-2">{tabs.map((tab, index) => <button key={tab} type="button" onClick={() => setActive(tab)} className={`rounded-lg border px-3 py-2 font-mono text-[9px] uppercase tracking-wider transition-colors ${active === tab ? "border-[#FF5A1F]/35 bg-[#FF5A1F]/[0.06] text-[#FF5A1F]" : "border-white/[0.08] text-white/45 hover:text-white"}`}>0{index + 1} {tab}</button>)}</div><div className="relative mt-5 min-h-[28rem] overflow-hidden rounded-2xl border border-white/[0.1] bg-[#1A1A1A] p-4 text-left shadow-[0_26px_52px_-24px_rgba(0,0,0,.88)] sm:p-7"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_50%_35%,rgba(255,90,31,.06),transparent_45%)]" /><AnimatePresence mode="wait"><motion.div key={active} initial={{ opacity: 0, y: reduceMotion ? 0 : 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: reduceMotion ? 0 : -8 }} transition={{ duration: .35, ease: "easeOut" }} className="relative z-10 h-full"><p className="mb-5 font-mono text-[9px] uppercase tracking-[.18em] text-[#FF5A1F]">{active} / product walkthrough</p><Visual reduce={reduceMotion} /></motion.div></AnimatePresence></div></div>;
}
