"use client";
import { motion, useReducedMotion } from "framer-motion";

const nodes = [["↳", "Reply"], ["◇", "Revenue playbook"], ["◫", "Prospect memory"], ["$", "Revenue context"], ["▤", "Sales constitution"]] as const;
const Node = ({ icon, label, index }: { icon: string; label: string; index: number }) => <motion.div initial={{ opacity: 0, y: 8 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .3 }} transition={{ duration: .35, delay: index * .1 }} className="flex min-w-0 items-center justify-center gap-2 rounded-lg border border-white/[0.1] bg-[#242424] px-2.5 py-3"><span className="text-[#FF5A1F]">{icon}</span><span className="truncate font-mono text-[8px] uppercase tracking-wider text-white/70">{label}</span></motion.div>;

export default function ResponsiveDecisionConvergence() {
 const reduce = useReducedMotion();
 return <div className="relative mx-auto mt-10 max-w-5xl overflow-hidden rounded-2xl border border-white/[0.1] bg-[#151515] p-4 shadow-[0_28px_60px_-25px_rgba(0,0,0,.9)] sm:p-8"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(255,90,31,.1),transparent_42%)]" />
 <div className="relative z-10 grid gap-3 sm:hidden"><div className="grid grid-cols-2 gap-2"><Node icon={nodes[0][0]} label={nodes[0][1]} index={0}/><Node icon={nodes[1][0]} label={nodes[1][1]} index={1}/></div><Node icon={nodes[2][0]} label={nodes[2][1]} index={2}/><Core reduce={reduce}/><div className="grid grid-cols-2 gap-2"><Node icon={nodes[3][0]} label={nodes[3][1]} index={3}/><Node icon={nodes[4][0]} label={nodes[4][1]} index={4}/></div><Approval /></div>
 <div className="relative z-10 hidden min-h-[24rem] place-items-center sm:grid"><Core reduce={reduce}/>{nodes.map(([icon,label],index)=>{const positions=["left-4 top-8","right-4 top-8","left-2 bottom-12","right-2 bottom-12","top-1/2 left-1/2 -translate-x-1/2 -translate-y-[12rem]"];return <div key={label} className={`absolute ${positions[index]} flex items-center gap-2 rounded-xl border border-white/[0.1] bg-[#242424] px-3 py-3`}><span className="text-[#FF5A1F]">{icon}</span><span className="font-mono text-[8px] uppercase tracking-wider text-white/70">{label}</span></div>})}<Approval /></div></div>;
}
function Core({ reduce }: { reduce: boolean | null }) { return <motion.div animate={reduce ? {} : { boxShadow:["0 0 0 rgba(255,90,31,0)","0 0 38px rgba(255,90,31,.35)","0 0 0 rgba(255,90,31,0)"] }} transition={{duration:3,repeat:Infinity,repeatDelay:3}} className="z-20 mx-auto grid h-28 w-28 place-items-center rounded-full border border-[#FF5A1F]/45 bg-[#FF5A1F]/[0.08] text-center shadow-2xl"><div><p className="font-mono text-[8px] uppercase tracking-[.15em] text-[#FF5A1F]">FrameLeads</p><p className="mt-2 text-[10px] font-bold text-white">DECISION CORE</p></div></motion.div>; }
function Approval() { return <div className="mx-auto w-fit rounded-full border border-[#FF5A1F]/30 bg-[#FF5A1F]/[0.06] px-4 py-2 font-mono text-[8px] uppercase tracking-wider text-[#FF5A1F] sm:absolute sm:bottom-3 sm:left-1/2 sm:-translate-x-1/2">Human approval selected</div>; }
